### ISSUE TITLE
AppImage - JavaScript issue.

### ISSUE THREAD

**Issue by Justinzobel** [Pong420/google-tasks-desktop#31]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/home/justin/.config/google-task-desktop/google-tasks-desktop'
    at Object.mkdirSync (fs.js:731:3)
    at Object.<anonymous> (/tmp/.mount_Googlers9QYR/resources/app.asar/electron/store.js:13:18)
    at Object.<anonymous> (/tmp/.mount_Googlers9QYR/resources/app.asar/electron/store.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by Pong420** [comment]
Seems same as #28. Have you try [2.0.2](https://github.com/Pong420/google-tasks-desktop/releases/tag/2.0.2)?

**Comment by Justinzobel** [comment]
This was 2.0.2 but I'm not sure what happened cause now it's working. I have rebooted since last attempt. If you want any details I'm happy to provide otherwise you're free to close the issue.

**Comment by Pong420** [comment]
Thanks for your report. I will close it first.
